layout_spectrum: 0.9916045
color:
  saturation: 0.8134328
  lightness: 0.7071118
  brandStrength: 1
  brandColors:
    - '#000000'
    - '#919191'
    - '#682E86'
    - '#FFC82E'
    - '#411D54'
  rhythmicContrast: 0.8997201
typography_spectrum: 0.1012127
name: Bethel Sports
